image: gradle:latest

stages:
  - build
  - test
  - check

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

before_script:
  - gradle --version

build:
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - gradle test

vulnerability_check:
  stage: check
  script:
    - chmod +x gradlew
    - ./gradlew dependencyCheckAnalyze
  artifacts:
    paths:
      - build/reports/*.html
